### ISSUE TITLE
Can not open ansys example-data result_files/d3plot

### ISSUE THREAD

**Issue by anlijun** [PucklaJ/dynareadout#38]
can not open file:
https://github.com/ansys/example-data/tree/master/result_files/d3plot
error msg:
Failed to open: The d3plot files are broken

**Comment by PucklaJ** [comment]
This file has an odd case for my algorithm to determine if it is single precision or double precision can not determine it. I improved the algorithm, but to fully support this file I also need to implement support for an NDIM value of 4. According to the documentation this means:
```
If 4 then element connectivies are unpacked in the DYNA3D database and NDIM is reset to 3
```

**Comment by PucklaJ** [comment]
I am still working on this bug. It's probably not fixed until tomorrow when I will create a new Release

**Comment by PucklaJ** [comment]
This has been resolved and tomorrow I will create a new Release

**Comment by anlijun** [comment]
> This has been resolved and tomorrow I will create a new Release

I installed dynareadout-24.1, this problem still occurs:
Failed to open: The d3plot files are broken
