### ISSUE TITLE
Can not open ansys example-data result_files/d3plot_beam

### ISSUE THREAD

**Issue by anlijun** [PucklaJ/dynareadout#39]
can not open file:
https://github.com/ansys/example-data/tree/master/result_files/d3plot_beam
error msg:
Failed to open: The USER IDENTIFICATION NUMBERS section is false (122445 != 4012)

**Comment by PucklaJ** [comment]
I am still working on this bug and it will probably not be ready until tomorrow when I will create a new Release

**Comment by PucklaJ** [comment]
I fixed it! I did not read all 64 EXTRA values and therefore my pointer was offset. Thank you for opening the issue. I want to ensure that every d3plot file can at least be opened without crashing and a correct error message.

**Comment by anlijun** [comment]
I installed dynareadout-24.1, this problem still occurs

Failed to open: The USER IDENTIFICATION NUMBERS section is false (122445 != 4012)

> I fixed it! I did not read all 64 EXTRA values and therefore my pointer was offset. Thank you for opening the issue. I want to ensure that every d3plot file can at least be opened without crashing and a correct error message.

I installed dynareadout-24.1, this problem still occurs:
Failed to open: The USER IDENTIFICATION NUMBERS section is false (122445 != 4012)
